#!/bin/bash
#
# https://github.com/docker-solr/docker-solr/blob/master/8.1/scripts/solr-demo
# 

set -euo pipefail

if [[ "${VERBOSE:-}" == "yes" ]]; then
    set -x
fi

. /opt/docker-solr/scripts/run-initdb

CORE=manufacturer_product

coresdir=/var/solr/data
CORE_DIR="$coresdir/$CORE"
if [ -d "$CORE_DIR" ]; then
  echo "$CORE_DIR exists; skipping core creation"
else

  start-local-solr
  echo "Creating $CORE"
  /opt/solr/bin/solr create -c "$CORE"
  echo "Created $CORE"

  CORE_URL=http://localhost:8983/solr/manufacturer_product
  SCHEMA_URL="$CORE_URL/schema"
  echo "Update schema on $SCHEMA_URL"

  curl -X POST -H 'Content-type:application/json' \
    --data-binary @/opt/solr/add-field-category.json $SCHEMA_URL

  curl -X POST -H 'Content-type:application/json' \
    --data-binary @/opt/solr/add-field-content.json $SCHEMA_URL

  curl -X POST -H 'Content-type:application/json' \
    --data-binary @/opt/solr/add-field-html_body.json $SCHEMA_URL

  curl -X POST -H 'Content-type:application/json' \
    --data-binary @/opt/solr/add-field-html_title.json $SCHEMA_URL

  curl -X POST -H 'Content-type:application/json' \
    --data-binary @/opt/solr/add-field-manufacturer_id.json $SCHEMA_URL

  curl -X POST -H 'Content-type:application/json' \
    --data-binary @/opt/solr/add-field-manufacturer_name.json $SCHEMA_URL
  
  curl -X POST -H 'Content-type:application/json' \
    --data-binary @/opt/solr/add-field-page_updated_at.json $SCHEMA_URL
  
  curl -X POST -H 'Content-type:application/json' \
    --data-binary @/opt/solr/add-field-product_url.json $SCHEMA_URL

  curl -X POST -H 'Content-type:application/json' \
    --data-binary @/opt/solr/replace-field-type-text_ja.json $SCHEMA_URL
  
  curl -X POST -H 'Content-type:application/json' \
    -d'{
      "set-property" : {"requestDispatcher.requestParsers.enableRemoteStreaming":true},
      "set-property" : {"requestDispatcher.requestParsers.enableStreamBody":true}
    }' "$CORE_URL/config"

  stop-local-solr

    # check the core_dir exists; otherwise the detecting above will fail after stop/start
    if [ ! -d "$CORE_DIR" ]; then
        echo "Missing $CORE_DIR"
        exit 1
    fi
fi

exec solr-fg