apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: app-admin 
  name: app-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-admin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app-admin
    spec:
      containers:
      - name: admin
        image: tc3jp/productsearch-app-admin:develop-1.0.15p1
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
