apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: calctr-cronjob
spec:
  schedule: "0 0 */7 * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: calctr-cronjob
        spec:
          restartPolicy: OnFailure
          containers:
          - args:
            - --proc=calctr
            - --calc_period=7
            image: tc3jp/productsearch-service:develop-1.0.15
            name: crawler
            env:
            - name: SPRING_JDBC_URL
              value: jdbc:mysql://mysql:3306/website_crawler?useSSL=false&nullNamePatternMatchesAll=true&allowPublicKeyRetrieval=true
            - name: SOLR_URL
              value: http://solr:8983/solr/manufacturer_product