apiVersion: batch/v1
kind: Job
metadata:
  name: delete-click-log-job
spec:
  template:
    metadata:
      labels:
        app: delete-click-log-job
    spec:
      restartPolicy: Never
      containers:
      - args:
        - "30"
        image: tc3jp/productsearch-delete-click-log:develop-1.0.15p2
        name: crawler
        env:
        - name: HOST
          value: mysql
        - name: PORT
          value: "3306"
        - name: USER
          value: root
        - name: PASSWORD
          value: mypassword
