/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.topcoder.web.crawler;

public class Application {
    public String getUsage() {
        return "java -jar website-cralwer.jar com.topcoder.web.crawler.App <website-id>";
    }

    public static void main(String[] args) {
        System.out.println(new Application().getUsage());
    }
}
