version: '3'
services:
  mysql:
    #image: mysql:8.0.12
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: website_crawler
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mypassword

